datagouv/hydra

- .circleci/config.yml
- setup.cfg
- udata_hydra/cli.py
- udata_hydra/datalake_service.py
- udata_hydra/kafka/consumer.py
- udata_hydra/utils/csv.py
Ultimate CI bike shedding (or yake shaving?) ☢️ 
Before working on a template, I wanted to test a few things on a real workflow, hence this PR.
This splits the CI workflow into multiples small steps (and adds linting in this case) rather than a big build and a small publish.
Plus side:
- I like the way the feedback is available: you know at a glance which step failed, either from Github or from Circle
- It provides a framework for more complex CI workflows (parallel task for example, here the linting is parallelized which is not very useful but still)
- Variables are cool
Minus:
- More lines in file — not sure if easier or harder to grasp
- There must be some overhead of spinning up multiple jobs instead of one, but it seems minor
> Test multipart CI workflow

- udata_hydra/cli.py
- udata_hydra/crawl.py
Instead of checking if the status has changed for the same URL we check for the same resource_id, so as to send a Kafka message whenever the resource availability has changed, regardless whether the URL was checked before for a different resource.
Fix https://github.com/etalab/udata-hydra/issues/19.
> Check by resource_id

- README.md
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_crawler.py
- tests/test_utils.py
- udata_hydra/cli.py
- udata_hydra/config.py
- udata_hydra/crawl.py
- udata_hydra/datalake_service.py
- udata_hydra/utils/csv.py
- udata_hydra/utils/http.py
Fix #31 
Sorry this is a pretty big PR but I encountered many problems while debugging #31.
Main changes:
- add `check-resource` CLI helper
- do not return in `finally` in `datalake_service.process_resource`, this was hiding a lot of errors
- do not reuse the crawl aiohttp request for downloading, it does not make sense (could be a HEAD for exemple) — also the timeouts should be different for those tasks
- add very import `deleted = FALSE` in `crawl.update_check_and_catalog`, this was triggering useless (and pretty strange ⚫ ⭐ ) loops
- fix tests that rightly failed because they were not aligned with what was supposed to happen
You should be able to `print(coucou)` from pretty much anywhere now 🐔. There's still a lot of refactoring TBD but let's start with that!
> Refactor crawling / analysis quite a bit

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_csv_analysis.py
- udata_hydra/analysis/csv.py
- udata_hydra/utils/file.py
- udata_hydra/utils/timer.py
This uses the `output_profile` from `csv-detective`, for which we need to analyse the whole file and not a sample.
This makes things significantly slower (cf below). I added a `Timer` class because that's something I've been doing a lot :-)
```
$ poetry run udata-hydra analyse-csv --url https://static.data.gouv.fr/resources/annuaire-des-diagnostiqueurs-immobiliers/20230211-210014/annuaire-diagnostiqueurs.csv
2023-02-13 09:51:45 dev.local asyncio[48697] DEBUG Using selector: KqueueSelector
2023-02-13 09:51:46 dev.local udata-hydra[48697] DEBUG [analyse-csv] download-file done in 0.9991s
2023-02-13 09:52:13 dev.local udata-hydra[48697] DEBUG [analyse-csv] csv-inspection done in 26.5583s
2023-02-13 09:52:13 dev.local udata-hydra[48697] DEBUG Converting from CSV to db for …
```
> Use profiling option from csv-detective

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_crawler.py
- tests/test_csv_analysis.py
- udata_hydra/analysis/csv.py
- udata_hydra/app.py
- udata_hydra/cli.py
- udata_hydra/migrations/main/20231102_drop_csv_analysis.sql
- udata_hydra/utils/db.py
- udata_hydra/utils/file.py
- udata_hydra/utils/timer.py
So I tried to add an API endpoint for analysis results and I realised the `csv_analysis` table was more of a hassle than anything — just like we discussed.
Thus `csv_analysis` is removed, interesting columns are integrated to `checks` and the `checks` API now handles csv analysis results.
> Remove csv_analysis, integrate into checks

- CHANGELOG.md
- udata_hydra/config_default.toml
- udata_hydra/context.py
Use `asyncpg` to configure a dedicated PostgreSQL schema: https://magicstack.github.io/asyncpg/current/api/index.html
By default it's configured to use the pre-defined `public` schema.
> allow to configure a dedicated PostgreSQL schema

- CHANGELOG.md
- tests/conftest.py
- tests/test_api.py
- udata_hydra/app.py
Following https://github.com/opendatateam/udata/pull/2815
`published` date has been removed and `modified` renamed to `last_modified`
> Update dates following udata refacto

- CHANGELOG.md
- tests/test_crawler.py
- udata_hydra/crawl.py
In `check_url`, send useful headers info to udata.
We're currently sending `content-type` and `content-length`, useful for preview.
> Send content-type and content-length header to udata

- CHANGELOG.md
- README.md
- tests/test_crawler.py
- udata_hydra/analysis/resource.py
More coherent with check:headers:content-length
> Rename analysis filesize to content-length

- CHANGELOG.md
- udata_hydra/crawl.py
Sleep for `SLEEP_BETWEEN_BATCHES` whether there are urls to crawl or not.
When most urls left to crawl are urls on which we backoff, we end up in a loop where we always have some urls `to_check` but can't and never sleep.
Seems like sleeping between all batches allow for a slower pace to crawl all urls as well, aside from the backoff reason.
> Sleep between all batches

- CHANGELOG.md
- udata_hydra/app.py
Add health route, that assert Postgres connection and returns a 200.
The Postgres connection tests runs a `SELECT 1`, similar to what has been done in PostgREST [in their ready route](https://github.com/PostgREST/postgrest/blob/e572d1d1a2ea14cd4505be2fa0c2c08e46d32997/src/PostgREST/Workers.hs#L295).
> Add health route

- tests/test_crawler.py
- udata_hydra/config_default.toml
- udata_hydra/crawl.py
We were currently waiting forever on ratelimit backoff, since we used last check without any limit of time.
We're now looking at a last check since a COOL_OFF_PERIOD.
In particular, we're waiting for a COOL_OFF_PERIOD if we've messed up or a simple BACKOFF_PERIOD if we've reached our ratelimit quota.
At the contrary, when receiving a 429, we only waited for a BACKOFF_PERIOD, which is not enough when we've messed up. Now we're waiting for a COOL_OFF_PERIOD.
Not sure if the backoff logic could be more readable, interested in suggestions.
___
Default values:
COOL_OFF_PERIOD  = 1day
BACKOFF_PERIOD  = 6 min
> Improve on the backoff logic

- CHANGELOG.md
- tests/test_crawler.py
- udata_hydra/crawl.py
We don't want to mark resources as unavailable on a 429 status code since it's the crawler's fault.
Setting check:available to None will override any existing values in extras. We should use this key to check the resource availability in the front.
See https://github.com/etalab/data.gouv.fr/issues/1092
> Set check:available to None in case of a 429

- CHANGELOG.md
- tests/test_api.py
- tests/test_cli.py
- tests/test_crawler.py
- udata_hydra/app.py
- udata_hydra/cli.py
- udata_hydra/config_default.toml
- udata_hydra/migrations/main/20230606_rev9_up_rev10.sql
Fix https://github.com/etalab/udata-hydra/issues/74
Add a constraint on resource_id unique, instead of the tuple (dataset_id, resource_id, url).
It means that on any resource update, we update URL value accordingly.
Past URLs that have been checked are kept in the `checks` table, thus keeping a trace of previous checked URLs if needed.
We also update the `purge_csv_tables` logic, that was expecting outdated URLs to be marked as deleted in the catalog.
But we can actually have URLs that disappear from the catalog, updated to the latest URL used for this resource.
Add unit test to describe buggy behavior
* There is one test on the load_catalog logic that creates multiple entries for a single resource
* And another test to raise a 500 on api udpate in case of multiple resource entries
* Add …
> Fix conflict on updating catalog with multiple entries for a resource

- CHANGELOG.md
- udata_hydra/crawl.py
See https://errors.data.gouv.fr/organizations/sentry/issues/3980/?alert_rule_id=2&alert_timestamp=1692701389542&alert_type=email&environment=production&project=2&referrer=alert_email.
`last_check` could have `headers` set to `None`, leading `json.loads(None)` to fail. We improve the `if` condition to ensure it isn't `None`.
> Fix last_check_headers when  headers is None

- CHANGELOG.md
- README.md
- udata_hydra/analysis/csv.py
Returns early with None when converting empty values to int, float, etc.
Currently, `smart_cast` first fails when trying `int("")`, then we try to `str2float("" default=None)`, and finally return None.
It ends up logging lots of errors:
```
WARNING Could not convert "" to int, defaulting to null
```
We also gain significant time (from ~30 to ~20 seconds on big file test): https://github.com/etalab/udata-hydra/blob/1a1361e68055f2a12df640a35b4c9e777298b38b/tests/test_csv_analysis.py#L41
[Related error](https://errors.data.gouv.fr/organizations/sentry/issues/4169/?project=21&query=&referrer=issue-stream&statsPeriod=14d#breadcrumbs) (that failed due to task timeout).
> Return None value early in csv-to-db

- udata_hydra/utils/db.py
Indeed, when loading catalog, all datasets are temporarily set to deleted=true. Fetching checks at this moment returns None.
It raises a "Check not found by id" error in process_resource.
Fix https://errors.data.gouv.fr/organizations/sentry/issues/2359
> Ignore deleted status when getting check by id

- CHANGELOG.md
- tests/conftest.py
- udata_hydra/app.py
Fix 404 bad request on resource created or updated call. See [sentry error](https://errors.data.gouv.fr/organizations/sentry/issues/2355/events/38a5e0eb55ec423ba5be55339d46e2bc/?project=12&referrer=events-table%2F%3Fproject%3D12).
Indeed, following https://github.com/opendatateam/udata/pull/2949 schema is set to None instead of an empty dict if not set.
> Allow for none value in resource schema

- CHANGELOG.md
- udata_hydra/cli.py
Prevent having duplicate parsing_tables being returned, making way fewer iteration for the job.
It reduces the number of rows returned from 75K to 12K on dev env for example.
Indeed, we then use the table name to delete it and update all checks that could have a reference to it as NULL.
We don't need to keep duplicate entry for each check.
> Select distinct parsing tables to delete

- pyproject.toml
- tests/test_crawler.py
- udata_hydra/analysis/csv.py
- udata_hydra/analysis/resource.py
- udata_hydra/app.py
- udata_hydra/crawl.py
Remove `pytz` module calls and use standard library `timezone` instead.
To quote [pytz's README](https://github.com/stub42/pytz/blob/master/src/README.rst#issues--limitations):
> This project is in maintenance mode. Projects using Python 3.9 or later are best served by using the timezone functionaly now included in core Python and packages that work with it such as tzdata.
> clean: remove deprecated pytz

- udata_hydra/analysis/helpers.py
Small fix regarding wrong types returns.
_Note:
In order to comply with the Python 3.9 retro-compatibility, we use only Python 3.9-compatible typings for now. The switch to cleaner >=3.10 typings are all gathered in the following draft PR once we switched to Python 3.11: https://github.com/datagouv/hydra/pull/108_
> fix: fix wrong types returns

- poetry.lock
For some reason, it seems CI tests are not passing anymore:
In CircleCI: `pyproject.toml changed significantly since poetry.lock was last generated. Run poetry lock [--no-update] to fix the lock file.` (see [here](https://app.circleci.com/pipelines/github/opendatateam/udata/4918/workflows/c779d033-74a2-4934-8775-f6a97321deee/jobs/30820?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary))
This PR fixes this on the go, it is just generated with a `poetry lock --no-update`
> build: fix lock file

- CHANGELOG.md
- tests/conftest.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_crawler.py
- udata_hydra/db/check.py
Since we added tests coverage (https://github.com/datagouv/hydra/pull/122), I saw that some API lines were not covered by tests.
This PR add some tests coverage, and slightly refactor API tests.
> tests: add tests

- README.md
If it's not installed, you get the following error:
```
ImportError: failed to find libmagic.  Check your installation
```
> Add info in the README on installing libmagic

- README.md
- tests/test_api.py
- udata_hydra/routes/checks.py
Minor cleaning PR.
- Remove unused imports
- Standardize spelling of "analysing" throughout code and docs
> clean: remove unused imports

- udata_hydra/crawl.py
Follows https://github.com/datagouv/hydra/pull/119
Use CRAWLING_URL instead of CRAWLING:
https://github.com/datagouv/hydra/blob/9b5ec880595de505f4a48b89637bfbde01e7f79b/udata_hydra/db/resource.py#L12
Fix https://errors.data.gouv.fr/organizations/sentry/issues/145139/?project=21&referrer=issue-stream
> Fix crawling status

- tests/test_api.py
- udata_hydra/routes/__init__.py
Follows https://github.com/datagouv/hydra/pull/119
We would actually like to have a redirection instead of a 404 on trailing slash or not, but for now let's keep it coherent with other routes at least.
> Add trailing slash on status route for coherence with others

- CHANGELOG.md
- udata_hydra/db/resource.py
- udata_hydra/routes/resources.py
Delete resource as a CRUD method.
More standard and useful for the upcoming https://github.com/datagouv/hydra/pull/132 PR (fully RESTful endpoints).
> refactor: delete resource as a CRUD method

- CHANGELOG.md
- udata_hydra/crawl/helpers.py
- udata_hydra/migrations/main/20240926_add_indexes.sql
This PR aims to drastically improve DB queries performance in two ways:
- Refactor function to get no_backoff domains, in order to avoid unnecessary queries
- Add PostgreSQL indexes to improve performance when querying:
- add indexes on `checks` table for `resource_id` and `created_at` columns
- add index on `catalog` table for `last_check` column
> refactor: refactor function to get no_backoff domains and add PostgreSQL indexes to improve DB queries perfs

- CHANGELOG.md
- README.md
- tests/test_api/test_api_resources_exceptions.py
- udata_hydra/app.py
- udata_hydra/routes/checks.py
- udata_hydra/routes/resources_exceptions.py
- udata_hydra/schemas/__init__.py
- udata_hydra/schemas/resource_exception.py
Fix several serious issues with resources exceptions routes:
- Fix serialisation of resource exception in API responses
- Added a proper Marshmallow schema for resource exception, so that it can be used for serialisation
- Allow posting of a new resources exception with no `tables_indexes`
- Added end-to-end API tests for all resources exceptions routes cases
- Remove resources exception routes to be excluded from auth, so that POST and DELETE are also authenticated routes
- Added documentation on how to make a curl request to the API to add a ressource exception
> fix: fix resources exceptions routes responses, add tests, update README

- .circleci/config.yml
- udata_hydra/__init__.py
- udata_hydra/routes/status.py
Save git commit hash in CI and use it for config and health check, in order to be able to check quickly which version is deployed without having to deal with comparing the dev versions, as an attempt to improving overall developer experience.
Note: not 100% sure the file is imported in the build :)
> feat: save git commit hash in CI and use it for health check

- CHANGELOG.md
- udata_hydra/cli.py
Similar to https://github.com/datagouv/data.gouv.fr/issues/1354 which was closed by https://github.com/datagouv/hydra/pull/95:
Add a `quiet` arg for `purge_check` and `purge_csv_table` CLIs, which makes the setting log level on `ERROR`, so that the CLI doesn't output logs by default and thus the infra doesn't send an email on each run of the CLI, unless there is an error.
> feat: add a quiet option for purge_check and purge_csv_table CLIs

- pyproject.toml
Coverage fails if coverage falls under 88%, which is the current tests coverage.
Not exactly sure if this would make the CI tests fail, but it's a good security feature for next development as it will at least show clearly in the CLI if coverage has lowered since that commit.
> tests: coverage fails if coverage falls under 88%

- CHANGELOG.md
- udata_hydra/crawl/check_resources.py
- udata_hydra/db/resource.py
Fix Sentry issue https://errors.data.gouv.fr/organizations/sentry/issues/145139/:
- A resource status was not the right one among valid resource statuses
- One resource status was not being used
> fix: fix wrong resource status

- CHANGELOG.md
- tests/test_api/test_api_resources_exceptions.py
- udata_hydra/analysis/csv.py
- udata_hydra/db/resource_exception.py
Closes https://github.com/datagouv/hydra/issues/198:
- Don't put empty values in `tables_indexes` columns of `resources_exceptions` table in the DB inser/update requests (happening when POSTing/PUTing `resources_exceptions`)
- Add test case to test the value when it's set to None
- Add a few exceptions catching related to `resources_exceptions` on the go, to secure the code
Note: the production table has been already updated so that all `resources_exceptions` have "{}" as the empty value (same as the default SQL value) when empty, so the error is already fixed with the current `resources_exceptions`:
`UPDATE resources_exceptions SET table_indexes = '{}' WHERE table_indexes IS NULL;`
> fix: fix empty table indexes

- .circleci/config.yml
- CHANGELOG.md
- Change deprecated Circle step name from `deploy`to `run`(see https://circleci.com/docs/migrate-from-deploy-to-run/)
- Remove workflows version key, which is deprecated since CircleCI 2.1 (see https://circleci.com/docs/configuration-reference/#workflow-version)
> ci: fix deprecated CircleCI config

- CHANGELOG.md
- udata_hydra/analysis/csv.py
- udata_hydra/crawl/helpers.py
- udata_hydra/utils/auth.py
Rewrite a few docstrings to use a more consistent syntax.
Since we use type hints extensively, we don't need to rewrite the types in the docstring, so we decided use the quite broadly standard [Google styleguide](https://google.github.io/styleguide/pyguide.html) for docstrings.
> docs: update docstrings

- tests/test_analysis/test_analysis_csv.py
- udata_hydra/analysis/resource.py
- udata_hydra/cli.py
- udata_hydra/crawl/check_resources.py
- udata_hydra/routes/checks.py
We're missing this feature: forcing analysis on a resource, independently of whether its content has changed since last check.
> Add option to force analysis even if resource has not changed

- CHANGELOG.md
- udata_hydra/db/check.py
- udata_hydra/routes/checks.py
Fix the 3rd issue in https://github.com/datagouv/data.gouv.fr/issues/1518.
This fixes the behaviour of the `/checks/all` endpoint, which was the only method using the `Check.get_all` CRUD method.
Also:
- remove useless import
- minor SQL order rewrite for better consistency with other SQL queries
> fix: fix get all checks CRUD method

- CHANGELOG.md
- tests/test_parquet_export.py
- udata_hydra/analysis/csv.py
- udata_hydra/analysis/errors.py
- Refactor ParseError as a generic exception to enrich Sentry with context and to inquire about Sentry errors like [#4096](https://errors.data.gouv.fr/organizations/sentry/issues/4096) when analysing CSV and creating DB tables
- Update deprecated Sentry SDK method `set_extra()` to `set_tags()`
- Update deprecated Sentry SDK method `push_scope()` to `new_scope()`
> fix: refactor ParseError to enrich Sentry with context and to inquire about Sentry errors like #4096

- CHANGELOG.md
- udata_hydra/analysis/csv.py
Fix typing issue, as `resource_id` was a `UUID` type instead of a `string` when passed to several methods, including the `ParseException` constructor.
> fix: fix type issue regarding resource_id

- CHANGELOG.md
- tests/test_cli.py
- udata_hydra/cli.py
This proved useful locally for me, to insert a new resource into my local catalog (or update an existing one), instead of having to do database shenaningans
> CLI to insert resource into local catalog

- .circleci/config.yml
- CHANGELOG.md
Closes https://github.com/datagouv/data.gouv.fr/issues/1465.
Goes hand-to-hand with the GitLab MR.
For now, the trigger is sent only when we push on `main`.
We can imagine other policies?
**EDIT:**
Refactored entirely to use the GitLab _scaffolding_ deploy script repository instead, as the intermediary between this CI and GitLab API for infra repo CI.
Remarks:
- As a first version, this only triggers a call to the deploy script (and thus to GitLab for deploying on dev environment) when pushing on main. Later, we can imagine deploying easily, I suggest to do it in another PR.
- This PR also includes a better separation of the build job into smaller steps, clearer and easier to debug. This cleaning job can be more clearly done in this dedicated [PR …
> ci: trigger GitLab deployment pipeline when pushing

- .circleci/config.yml
- CHANGELOG.md
- pyproject.toml
- Add install step cache fallback
- Parallelize the execution of tests among 4 CircleCI executors. This results in a gain of an average approx. ~40% on the total CI execution time (around 60% specifically on the tests job)
- Note 1: For this, we need to deactivate the maximum coverage rule for test success, as each executor reach a different coverage. The gain makes it worth to deactivate this feature, as anyway we can monitor the coverage, and we can activate the minimum coverage threshold when running locally if necessary.
- Note 2: it has also been tested with 2 executors, 3 executors and 10 executors, but 4 executors seems like a good balance for time gains
Before:
After:
> ci: parellelize tests in CI

- CHANGELOG.md
- tests/conftest.py
- tests/test_analysis/test_analysis_csv.py
- tests/test_analysis/test_analysis_csv_exceptions.py
- tests/test_analysis/test_analysis_other_formats.py
- tests/test_crawl/test_backoff.py
- tests/test_crawl/test_crawl.py
- udata_hydra/analysis/csv.py
- udata_hydra/analysis/resource.py
- udata_hydra/cli.py
- udata_hydra/crawl/check_resources.py
- udata_hydra/crawl/preprocess_check_data.py
- udata_hydra/crawl/select_batch.py
- udata_hydra/db/__init__.py
- udata_hydra/db/check.py
- udata_hydra/db/resource.py
- udata_hydra/routes/checks.py
Needs to be merged after https://github.com/datagouv/hydra/pull/163.
This is a refactoring PR to remove many non necessaries SQL queries, using the existing data in the code instead of re-querying it.
> refactor: remove non necessary SQL queries

- .circleci/config.yml
- CHANGELOG.md
Use a bash file instead of text file to store env vars across CI jobs, as it is cleaner and more idiomatic.
> ci: use a bash file instead of text file to store env vars across CI jobs

- CHANGELOG.md
- tests/test_cli.py
- udata_hydra/cli.py
For example, [this resource](https://www.data.gouv.fr/fr/datasets/liste-des-experiences-partagees-par-les-usagers/#/resources/91ea5a74-35f9-48d3-86cb-4407bf766927) stills has `analysis:last-modified-detection : harvest-resource-metadata` even though the dataset is not harvested anymore.
> Update harvest_modified_at on load catalog

- CHANGELOG.md
- udata_hydra/analysis/resource.py
- udata_hydra/utils/errors.py
Fixes unhandled IOExceptions in Sentry [example](https://errors.data.gouv.fr/organizations/sentry/issues/250309/?project=21)
> Unify exceptions

- CHANGELOG.md
- tests/test_crawl/test_crawl.py
- tests/test_db/test_db_resources.py
- udata_hydra/cli.py
- udata_hydra/config_default.toml
- udata_hydra/crawl/__init__.py
- udata_hydra/db/resource.py
I am wondering if we should also clean statuses that are not within the [current list](https://github.com/datagouv/hydra/blob/df2a916b2c77e595b40d50d2aa53924c580aa3ac/udata_hydra/db/resource.py#L9) in `Resource.clean_up_statuses`
> Reset stuck statuses

- CHANGELOG.md
- udata_hydra/analysis/geojson.py
Instead of using subprocess, we use tippecanoe python lib, that should use correct bin path for tippecanoe
See the content of `/lib/python3.11/site-packages/tippecanoe/__init__.py`
> Try using tippecanoe python lib

- CHANGELOG.md
- udata_hydra/cli.py
Without this, we end up trying to delete the same parsing_table mutliple times.
It doesn't fail, but it wastes useless time deleting already deleted contents
> Select DISTINCT parsing table in purge_selected_csv_tables CLI

- .circleci/config.yml
- CHANGELOG.md
This PR fixes a PostgreSQL version mismatch between CI and local development environments.
Problem
CI environment: Used PostgreSQL 11.15 (cimg/postgres:11.15)
Local development: Uses PostgreSQL 15 (postgres:15 in docker-compose.yml)
This version mismatch could cause inconsistent test behavior and potential issues in production
Solution
Updated the CircleCI configuration to use PostgreSQL 15.13 (cimg/postgres:15.13) to match the Docker Compose setup.
> ci: Update PostgreSQL version in CI to match Docker Compose (15.13)

- .circleci/config.yml
- CHANGELOG.md
Taking some inspiration from [this](https://github.com/datagouv/api-tabular/pull/50) and [this](https://github.com/datagouv/api-tabular/pull/38) recent CI refactoring PRs of TabularAPI, this PR streamlines the CircleCI configuration by:
- **Switching to Docker images which include Poetry 2** instead of manually installing Poetry in each job
- **Simplifying dependency installation** - using `poetry install` directly instead of creating a local Poetry venv
- **Using `-slim` variants of Docker images** for jobs that don't need full system dependencies (install, lint, build, publish)
- **Using full Python image for tests** where system dependencies like `libmagic` is required
- **Using flexible Python version** - `3.11` instead of `3.11.10` for automatic patch updates
- **Reduced …
> ci: simplify ci

- CHANGELOG.md
- tests/test_crawl/test_crawl.py
- udata_hydra/crawl/check_resources.py
Closes https://github.com/datagouv/hydra/issues/310
Related discussion: https://mattermost.incubateur.net/betagouv/pl/1qt9fgsjw7yo3y8ii7u6y4xdmh
Reduces congestion in high-priority queue while maintaining udata synchronization as a priority.
**Priority resources in DB** (`priority=True`): Crawl and analysis use "default" priority  
**Non-priority resources in DB** (`priority=False`): Crawl and analysis use "low" priority  
**Udata notifications**: Always "high" priority (no change)
> fix: optimize queue priorities for resource processing 

- CHANGELOG.md
- tests/test_analysis/test_analysis_csv.py
- tests/test_analysis/test_geojson.py
- udata_hydra/analysis/geojson.py
Partly helps https://github.com/datagouv/data.gouv.fr/issues/1847:
- Split `csv_to geojson_and_pmtiles()` function into a new intermediary function `csv_to_geojon()`, in order to better unit test and benchmark the csv to PMtiles workflow later ; so that functions `csv_to_geojon()` and `geojson_to_pmtiles()` can now be called by the tests or from the CLI independently with new, consistent arguments and return types for testing.
Also, on the way:
- Use of `pathlib.Path` instead of strings for file paths whenever possible in `csv_to geojson_and_pmtiles()`, `csv_to_geojon()` and `geojson_to_pmtiles()`, for safer, cleaner, and more readable file operations.
- Adapt tests to cleanup the test data files through a `cleanup` function argument instead of a mock on `os`.
The branch `benchmark` will …
> refactor: split `csv_to_geojson_and_pmtiles()` into intermediary function `csv_to_geojon()` for tests

- CHANGELOG.md
- udata_hydra/utils/errors.py
Closes https://github.com/datagouv/hydra/issues/306
Fix custom exception which enriches Sentry with tags and captures the exception with full stack trace when it's actually raised and caught.
**Wrong timing - auto-capture in `__init__`**  
- The original implementation captured the exception in the `__init__` method  
- At this point, the exception hasn't been raised yet, so there's no stack trace  
- Sentry receives an exception without any context about where it occurred  
We now capture the exception in the `__str__` method . This method is called when the exception is converted to string  which happens after the exception is raised and has a full stack trace . Sentry receives the complete context: exception + stack trace + custom tags  
We also tried another implementation with manual …
> fix: fix ExceptionWithSentryDetails to include Python stack trace

- CHANGELOG.md
- udata_hydra/logger.py
We were using the deprecated `sentry_sdk.Hub.current` API in the `stop_sentry()` function in `logger.py`.
Warning message:
_SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API_
According to [the Sentry 1.x to 2.x migration guide](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x), the Hub-based APIs are deprecated and should be replaced with the new scope-based approach.
> fix: fix deprecated Sentry method

- CHANGELOG.md
- udata_hydra/analysis/csv.py
- udata_hydra/analysis/geojson.py
- udata_hydra/utils/errors.py
In `await handle_parse_exception(e, table_name, check)` we update the check in db but we don't refetch the content, therefore sending an incomplete check payload to udata in `await helpers.notify_udata(resource, check)`
> Return updated check in `handle_resource_exception` to send the right payload to udata

- CHANGELOG.md
- tests/conftest.py
- tests/test_analysis/test_analysis_parquet.py
- udata_hydra/analysis/parquet.py
- udata_hydra/analysis/resource.py
- udata_hydra/cli.py
- udata_hydra/config_default.toml
- udata_hydra/db/resource.py
- udata_hydra/utils/__init__.py
- udata_hydra/utils/geojson.py
- udata_hydra/utils/parquet.py
So that they have a preview ✨ I am not sure what a good size limit would be, as parquet file are quite extensive, maybe 50Mo? We still have the exception mechanism anyway
Insight: the refactoring of `udata_hydra/analysis/resource.py` is to get the resource's format from the catalog only once
> Enable to analyse and insert parquet files
