datagouv/hydra

CHANGELOG.md
tests/test_crawler.py
udata_hydra/analysis/csv.py
udata_hydra/analysis/resource.py
udata_hydra/app.py
udata_hydra/crawl.py

We want to have standardized dates with timezones specified to send as udata extras.

Specify timezone in dates

---

tests/test_crawler.py
udata_hydra/crawl.py

If the domain doesn't return ratelimit infos correctly or we've messed up, we can receive a 429 status code.
In this case, we backoff and wait for BACKOFF_PERIOD before crawling again.
Note : We may need to take into account that we a check can lead to subsequent requests being made (ex: download), that may not show at check_url time.

Backoff on 429 status code

---

CHANGELOG.md
udata_hydra/cli.py
udata_hydra/config_default.toml
udata_hydra/utils/file.py

Useful to specify a shared temporary folder

Make temporary folder configurable

---

CHANGELOG.md
udata_hydra/cli.py
udata_hydra/logger.py

Fix https://github.com/datagouv/data.gouv.fr/issues/1354
Made the progress bar optional as well as setting log level on ERROR

Add a quiet option on load catalog

---

.pre-commit-config.yaml
tests/test_api.py
udata_hydra/crawl.py

Very minor fixes on the go:
- Add a docstring
- Fix a comment typo
- Fix pre-commit with updated Ruff args

clean: minor docs and linting fixes

---

CHANGELOG.md
README.md

- Fix wrong `docker compose` command in README
- Update outdated `docker compose` command in README
- Add more details about `pytest` command in README
- Fix typos in CHANGELOG

fix: fix docs

---

CHANGELOG.md
tests/test_api.py
udata_hydra/routes/__init__.py
udata_hydra/routes/status.py

- Fix health check endpoint route which was wrongly removed
- Add test for API health check endpoint to make sure this endpoint is working as expected

Fix health check endpoint

---

tests/conftest.py
tests/test_api.py
tests/test_other_formats_analysis.py
tests/test_parquet_export.py
udata_hydra/cli.py
udata_hydra/db/check.py
udata_hydra/routes/checks.py
udata_hydra/routes/resources.py

Minor PR for better method args and more type hints.

clean: better args and types

---

udata_hydra/analysis/csv.py
udata_hydra/analysis/helpers.py
udata_hydra/analysis/resource.py
udata_hydra/cli.py
udata_hydra/context.py
udata_hydra/crawl.py
udata_hydra/db/check.py
udata_hydra/logger.py
udata_hydra/routes/checks.py
udata_hydra/utils/app_version.py
udata_hydra/utils/file.py

Minor PR.
- Fix a few type hints
- Better type hints (use of <3.10 style `Optional`instead of `Union[...,None]`)
- Add comment and modify doctrings

clean: fix type hints

---

README.md

This follows #130, and the associated [PR in udata](https://github.com/opendatateam/udata/pull/3130).

Document the settings needed in udata to publish resource events

---

CHANGELOG.md
udata_hydra/analysis/resource.py
udata_hydra/logger.py

docs: fix typos

---

CHANGELOG.md
udata_hydra/__init__.py

Fix and simplify project metadata loading.

fix: fix project metadata loading

---

CHANGELOG.md
udata_hydra/config_default.toml
udata_hydra/logger.py
udata_hydra/routes/status.py

Related to an infrastruture change/PR.

fix: use ENVIRONMENT from config file instead of env var

---

CHANGELOG.md
pyproject.toml
udata_hydra/__init__.py

- Clean changelog to make it consistent with a section dedicated to 1.1.0 changes and a section dedicated to 2.0.0 changes
- Remove useless section in pyproject.toml

docs: clean changelog

---

CHANGELOG.md
tests/test_cli.py
udata_hydra/cli.py

Closes https://github.com/datagouv/hydra/issues/172

refactor: refactor purge_checks CLI to use a date limit instead of a number

---

CHANGELOG.md
tests/test_cli.py
udata_hydra/analysis/csv.py
udata_hydra/cli.py

Closes https://github.com/datagouv/hydra/issues/180
- Fix typing issue using minicli for analysis-csv CLI
- Fix method to get record columns in analysis-csv method
- Secure some cases in analysis-csv logic
- Add basic tests for analyse-csv CLI

fix: fix analysis csv CLI

---

CHANGELOG.md
udata_hydra/cli.py

Relative to Sentry error https://errors.data.gouv.fr/organizations/sentry/issues/144725

clean: more informative error relative to check resource CLI

---

CHANGELOG.md
README.md

Fix some typos in README related to curl commands examples.

docs: fix README

---

CHANGELOG.md
udata_hydra/analysis/resource.py
udata_hydra/db/resource.py

This needs to change all statuses in the DB from `PROCESSING_RESOURCE` to `ANALYSING_RESOURCE`.
(and maybe, to make sure, also `TO_PROCESS_RESOURCE` to `TO_ANALYSE_RESOURCE`)

fix: resource status

---

CHANGELOG.md
tests/test_crawl/test_crawl.py
udata_hydra/crawl/select_batch.py
udata_hydra/migrations/main/20241023_alter_foreign_key.sql

Closes https://github.com/datagouv/data.gouv.fr/issues/1542

fix: crawl resources with no last check

---

udata_hydra/analysis/csv.py
udata_hydra/analysis/resource.py

fix: fix type issues

---

CHANGELOG.md
udata_hydra/analysis/csv.py

Fix unhandled Sentry issue #4195 https://errors.data.gouv.fr/organizations/sentry/issues/4195/?project=21&query=error.unhandled%3Atrue&referrer=issue-stream&statsPeriod=14d

fix: fix sentry issue #4195

---

udata_hydra/crawl/helpers.py
udata_hydra/crawl/process_check_data.py
udata_hydra/routes/status.py

Another cleaning PR:
- Remove useless types and import
- Add a few type hints
- Slight refactor of some functions

clean: clean types and refactor some functions

---

CHANGELOG.md
udata_hydra/analysis/csv.py

Minor cleaning: remove unused arg in function.

clean: remove unused arg

---

udata_hydra/migrations/main/20250108_add_indexes.sql

Added two new indexes to the catalog table to improve query performance:
1. `status_deleted_idx` on `(status, deleted)`:
- Improves performance of resource filtering queries from ~4.5s to ~0.5s
- Used in `Resource.get_excluded_clause()` which filters resources for crawling
2. `last_check_priority_idx` on `(last_check, priority)`:
- Improves performance of batch selection queries
- Used in `select_batch_resources_to_check()` for resource processing
Performance was tested using `EXPLAIN ANALYZE` on the main queries:
Resource filtering query (status/deleted): 4.5s → 0.5s
Batch selection query: consistently performs at ~0.1s with caching
These indexes will improve the overall performance of the crawling pipeline without any code changes required. The trade-off of additional disk space for …

feat: add indexes to improve resource filtering and batch selection

---

CHANGELOG.md
setup.cfg

Remove unused `setup.cfg` file.

clean: remove unused setup.cfg

---

CHANGELOG.md
docker-compose.yml
udata_hydra/analysis/csv.py
udata_hydra/cli.py
udata_hydra/utils/errors.py
udata_hydra/utils/file.py

- https://github.com/datagouv/hydra/issues/242
- https://github.com/datagouv/hydra/issues/250

Fix various issues

---

CHANGELOG.md
tests/test_analysis/test_analysis_csv.py
udata_hydra/analysis/csv.py
udata_hydra/analysis/resource.py
udata_hydra/crawl/preprocess_check_data.py
udata_hydra/utils/__init__.py
udata_hydra/utils/http.py

Fix https://github.com/datagouv/hydra/issues/137

Reset related udata metadata when sending

---

CHANGELOG.md
poetry.lock
pyproject.toml
tests/data/catalog.csv
tests/test_analysis/test_analysis_csv.py
udata_hydra/analysis/csv.py
udata_hydra/analysis/helpers.py
udata_hydra/migrations/csv/20250626_delete_datetime_iso_references.sql

Following https://github.com/datagouv/csv-detective/pull/130 & https://github.com/datagouv/csv-detective/pull/132

Fix datetime insertion in db

---

CHANGELOG.md
udata_hydra/routes/status.py

Previous fix create `ZeroDivisonError` issues

Fix crawler endpoint bis

---

CHANGELOG.md
README.md

- Fix typos and example commands in README
- While we're at it, add emojis to sections of README, because... why not

docs: fix README typos

---

CHANGELOG.md
tests/test_analysis/test_analysis_csv.py
udata_hydra/analysis/csv.py

Fixes https://github.com/datagouv/hydra/issues/334

Better discriminate long column names
